### ISSUE TITLE
Mapping Libraries and Campuses

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#11]
https://github.com/psu-libraries/psulib_blacklight/wiki/Library-Faceting-and-Locations-Management

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 21, 2018, 11:53

changed title from **Add{-ing-} a library facet** to **Add a library facet**

**Comment by banukutlu** [comment]
In GitLab by @tbd3 on Jun 22, 2018, 11:31

The library facet can be keyed off the |m in the 949.

**Comment by banukutlu** [comment]
In GitLab by @tbd3 on Jul 3, 2018, 14:38

Library facet has been added by Maryam.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 10, 2018, 09:52

changed title from **{-Add a library facet-}** to **{+Library and Location Indexing+}**

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 10, 2018, 09:52

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jul 10, 2018, 09:52

Updated with notes from our meeting. This work should be moved to a branch but we've got a good start here!

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 16, 2018, 14:18

assigned to @mxk128

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 17, 2018, 15:45

mentioned in commit 2dfaebc9272de4718c7aa46f0b491e5d6ff28af3

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 14, 2018, 16:54

created branch [`11-library-and-location-indexing`](https://git.psu.edu/i-tech/psulib_traject/compare/master...11-library-and-location-indexing)

**Comment by banukutlu** [comment]
This feature needs to be explored further before development work to begin.

**Comment by cdmo** [comment]
as per convo with @ruthtillman, this issue will be just for libraries and campuses, locations will be done in #121
