### ISSUE TITLE
Refactor psulib_marc.rb

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#119]
- [x] move subject and genre work out of psulib_marc.rb
- [x] get rid of process_formats and move specs to its own formats specs
- [x] refactor process_publication_date and MarcPubDateProcessor should be thread-safe

**Comment by cdmo** [comment]
So should this go to the backlog again because 2/3 of the tasks are done?

**Comment by banukutlu** [comment]
> So should this go to the backlog again because 2/3 of the tasks are done?

yup 👍
