### ISSUE TITLE
Location mapping

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_traject#121]
https://github.com/psu-libraries/psulib_blacklight/wiki/Library-Faceting-and-Locations-Management

Required by https://github.com/psu-libraries/psulib_blacklight/issues/269

**Comment by ruthtillman** [comment]
Controlled list of excludes is here: https://github.com/psu-libraries/psulib_blacklight/wiki/Library-Faceting-and-Locations-Management#locations-advanced-search

**Comment by ruthtillman** [comment]
👍
