### ISSUE TITLE
Index and display titles

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#14]
In GitLab by @rkt6 on Aug 16, 2018, 11:35

https://github.com/psu-libraries/psulib_blacklight/wiki/Title-Fields-Indexing-and-Display

To-do:

* [x] Create title statement for display. `245abcfgknps` including vernacular. These should be used for the main title on a record page and the linked title in a search result. Vernacular must be displayed in search result snippets
* [x] Create a uniform title for display. `130adfklmnoprs:240adfklmnoprs:730ail` including vernacular. Uniform titles are a common way of referring to a work which can be called many things.
* [x] Create additional titles display. `210ab:246iabfgnp:247abcdefgnp:740anp` including vernacular. These include subtitles former titles, and uncontrolled versions of the title.
* [x] slice ` --` off this in cases from 505 for related titles `title_related_tsim`? Trim punctuation doesn't handle it

To-review (already in Traject and we should decide how we use and whether we remove): 

* [x] title_t 245a - first part of title. Can/should be used for exact matches and for general title index - to be handled in https://github.com/psu-libraries/psulib_blacklight/issues/180
* [x] title_display / title_vern_display - 245a. May want to deprecate.
* [x] subtitle_t - 245b. Subtitle. Unsure whether it will be useful. May need to deprecate.
* [x] subtitle_display / subtitle_vern_display - 245b, came with traject. Deprecate.

Required by https://github.com/psu-libraries/psulib_blacklight/issues/180

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 16, 2018, 11:39

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 6, 2018, 11:07

Fields added: 

- title_245ab_t
- uniform_title_display
- uniform_title_vern_display
- additional_title_display
- additional_title_vern_display
- related_title_display
- related_title_vern_display
- series_title_display
- title_related_t

Fields removed:

- subtitle_t
- subtitle_display
- subtitle_vern_display

Fields renamed:

- title_series_t to series_title_t

Branch `issue-14-title-adds-edits-deletes`

**Comment by ruthtillman** [comment]
so FYI I never merged this branch but it's here https://git.psu.edu/i-tech/psulib_traject/blob/issue-14-title-adds-edits-deletes/psulib_config.rb

**Comment by banukutlu** [comment]
new branch https://github.com/psu-libraries/psulib_traject/tree/%2314-index-and-display-titles

**Comment by cdmo** [comment]
@ruthtillman we see that you added `title_related_tsim` but kept `title_added_entry_tsim`. Was that intentional? Most of `title_added_entry_tsim` is encapsulated in `title_related_tsim`, except for a few subfields. It appears to me that both of these fields are trying to capture "potentially related to the title" type fields, but that `title_related_tsim` is a better version? No?

**Comment by ruthtillman** [comment]
@cdmo yes, but one could the 730 and 740 out of related. Added entry is a bit different than related.

**Comment by banukutlu** [comment]
So here are the mappings for them:

`title_added_entry_tsim`
```
  700gklmnoprst
  710fgklmnopqrst
  711fgklnpst
  730abcdefgklmnopqrst
  740anp
```

`title_related_tsim`
```
  700lktmnoprs
  710lktmnoprs
  711lktmnoprs
  730adfgklmnoprst
  740anp
  and bunch of other fields
```

740 is exactly same and small differences in others. Looking here https://github.com/psu-libraries/psulib_blacklight/wiki/Title-Fields-Indexing-and-Display we will use related field for display but what are we planning to do with added entry field?

**Comment by ruthtillman** [comment]
it may be more relevant for title searching. Essentially:

In searching limited to title, we will want to include added entries but not relateds.

Relateds would show up in general keywords and also display in the record, etc. They're essentially two similar but different things. so putting them under the same header in the catalog record would be an ishy choice.

**Comment by banukutlu** [comment]
OK makes sense, added entry is currently part of title search so we won't add related for title search then?

**Comment by banukutlu** [comment]
@ruthtillman In the `notes for indexing  and display` section of this issue description there was this note. (moved to wiki page now)
`In titles, retain punctuation.`
Looking at the branch changes search fields does not trim but most of the display fields does: 
main title display, uniform title display and related title display trims but  additional title display does not trim. Just wanted to confirm on these if that is the exact behavior we want.

**Comment by ruthtillman** [comment]
@banukutlu We'll want to retain the punctuation within the title (e.g. / ) but I think not at the end. Let's trim additional display too.

**Comment by banukutlu** [comment]
@ruthtillman title fields mapped from `245a` vs `245ab`:  Which one will be used for keyword search, which one for title search? 

@cdmo

**Comment by ruthtillman** [comment]
245ab for keyword. 245a would be exact front title match but we may also want to do match on 245ab. Something like weight 245a at 1, and 245ab at .8 or somesuch.

**Comment by banukutlu** [comment]
@ruthtillman wanted to confirm that we won't have a seperate vernacular field for series title?

**Comment by ruthtillman** [comment]
@banukutlu at this point I don't think so, no.

**Comment by banukutlu** [comment]
@ruthtillman how are we going to display vernacular titles in search results and single record views? do you have an example link to share which would give us an idea?

**Comment by cdmo** [comment]
@ruthtillman do you know of a record where the `505t` contains the trailing double-hyphen?

**Comment by ruthtillman** [comment]
@cdmo 12741571

**Comment by ruthtillman** [comment]
@banukutlu what I'd like to do is display

Vernacular title as title display + link
Latin character title below
 
Somewhat like this but with _only_ the vernacular title linked: https://catalog.princeton.edu/?f%5Blanguage_facet%5D%5B%5D=Chinese&page=6&q=&search_field=all_fields

and/or like this http://search.library.yale.edu/catalog?utf8=%E2%9C%93&adv%5B1%5D%5Bfield%5D=all_fields&adv%5B1%5D%5Bvalue%5D=&adv%5B2%5D%5Bop%5D=AND&adv%5B2%5D%5Bfield%5D=title&adv%5B2%5D%5Bvalue%5D=&adv%5B3%5D%5Bop%5D=AND&adv%5B3%5D%5Bfield%5D=author&adv%5B3%5D%5Bvalue%5D=&f%5Blanguage_facet%5D%5B%5D=Chinese&range%5Bpub_date_sort%5D%5Bbegin%5D=&range%5Bpub_date_sort%5D%5Bend%5D=&commit=Search&search_field=advanced

but with the vernacular and transliterated titles reversed.

**Comment by cdmo** [comment]
@mkutch provided me with this "binary" marc version of [12741571](https://psu.box.com/s/tijs7pnrxzgsqrgk1bp59iev0zhn6vfy). 0558d475961b07092282fd3cdc6f3142b9829118 processed it.

**Comment by cdmo** [comment]
@mkutch found an instance, [catkey 420](https://blackcat01qa.libraries.psu.edu/catalog/420), with a trailing slash. We should probably take care of this too, right @ruthtillman?

**Comment by banukutlu** [comment]
we will not worry about the trailing slashes in 550t since they are only for keyword search.

**Comment by ruthtillman** [comment]
Results look good. Tested searches for titles, subtitles, series titles, related titles, and chapter titles!
