### ISSUE TITLE
Hourly extracts from Sirsi

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#143]

**Comment by cdmo** [comment]
@mkutch and I created the hourly data directories, and I'm working on updating the rake task to handle hourly and daily now

**Comment by cdmo** [comment]
The hourly data is now appearing, @mkutch has done her job. Now I will work on importing this data on the traject side.

**Comment by cdmo** [comment]
Pending resolution to https://github.com/psu-libraries/psulib_blacklight/issues/286

**Comment by cdmo** [comment]
All set
