### ISSUE TITLE
Mapping note fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#15]
https://github.com/psu-libraries/psulib_blacklight/wiki/Note-Fields-Index-and-Display

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 09:24

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 09:55

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 11:12

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 11:21

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 11:22

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 11:29

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 21, 2018, 13:19

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 09:34

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 22, 2018, 11:33

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 4, 2018, 15:50

assigned to @rkt6

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 4, 2018, 15:50

assigned to @acg44 and unassigned @rkt6

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Sep 6, 2018, 11:04

changed the description

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Sep 6, 2018, 11:07

changed the description

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Sep 6, 2018, 11:21

changed the description

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Oct 3, 2018, 10:24

changed the description

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Oct 3, 2018, 11:27

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Oct 3, 2018, 12:03

Ruth - review 510s because they're a bit weird.

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Oct 3, 2018, 12:06

changed the description

**Comment by cdmo** [comment]
[wiki page](https://github.com/psu-libraries/psulib_blacklight/wiki/Note-Fields-Index-and-Display)

**Comment by cdmo** [comment]
@ruthtillman see https://github.com/psu-libraries/psulib_traject/issues/15#issuecomment-426790457

Not sure what that comment means, looks like it came over with the migration from GitLab but maybe never resolved?

**Comment by cdmo** [comment]
`505t` is already indexed in title related, but for the TOC display I'll use `505agrt` to start.

Here is a sample of what that resulted in:

```
184365       toc_ssim                  (from t.p.) I. An account of the fundamental principle of popery, and of the insufficiency of the proofs which they have for it -- II. An answer to six queries proposed to a gentle women of the Church of England, by an emissary of the church of Rome.
184366       toc_ssim                  I. Shewing, that through the instances collected in the said ms. had been pertinent to the editors design, yet that would not have been sufficient for obtaining their cause -- II. Shewing, that the instances there collected are indeed not pertinent to the editors design, for vindicating the validity of the deprivation of spiritual power by a lay-authority.
188083       toc_ssim                  A proclamation forbidding all levies of forces without His Majesties expresse pleasure, signified under his great seale and all contributions or assistance to such levies (pp. 1-12) -- His Majesties declaration to all his loving subjects occasioned by a false and scandalous imputation laid upon His Majestie of an intention of raising or leavying war against his Parliament and of having raised force to that end (pp. 13-26) -- His Majesties delcaration and profession disavowing any preparations or intentions in him to levie warre against his Houses of Parliament (pp. 27-28) -- The declaration and profession of the Lords now at York, and others of His Majesties Privie Councell disavowing that they see any apparence of preparations or intentions in His Majestie to leavie warre against his Parliament (pp. 29-30).
188578       toc_ssim                  Iris -- An address to the unsuccessful lover -- The tear -- Inconstancy -- The cottagers -- An invocation to Venus -- The knitting girl -- The forsaken lady -- An old story -- The flame of love -- Molly Carr -- Myra.
189416       toc_ssim                  [1] The Jesuits upon the scaffold, for severall capitall crimes by them committed in the province of Guienne. By Peter Jarrigius ... -- [2] The calumnies of james Beaufes refuted. By the same author -- [3] Secret insructions for the superiours of the Societie of Jesus. Faithfully rendred out of the Latine -- [4] A discourse of the reasons why the Jesuits are so generally hated. Orginally written, by Fortunius Galindus -- [5] A discovery of the Society in relation to their politicks. Written originally, by a well-wisher to the Jesuist -- [6] The prophecy of Saint Hildegard fulfilled in the Jesuits.
```

**Comment by cdmo** [comment]
`521| *|3ab:521|8*|3ab:521|3*|3ab:521|4*|3ab`

Should we change that to "Audience Notes"? So as not to confuse with mapping of `385`?

Here's a sample of what `521| *|3ab:521|8*|3ab:521|3*|3ab:521|4*|3ab` comes up with:

```
2701963               "Intended to serve as a voice for the movement community in Kansas and Kansas City, Missouri."
2702072               "This mag is not just for mill workers, the title simply acknowledges the important work they do in Pgh. The Herald is for all working people: homemakers, office employees, retirees, nurses, teacher, bus drivers, bartenders, you name it."
2729477               "A journal for Conservatives."
2829255               "Labor."
2829729               "Labor."
2829733               "Labor."
2829755               "Labor."
2829756               "Labor."
2829757               "Labor."
```

**Comment by ruthtillman** [comment]
Yep, let's change the 521 label.

**Comment by cdmo** [comment]
For abstracts, I went with 520ab as a first stab, here's some stuff

```
194024       abstract_ssm              On the parliamentary union of Great Britain and Ireland.
198725       abstract_ssm              "Labor is a national paper owned by ... unions with membership in the railroads, airlines, and related transport fields in both the United States and Canada" (varies)
2257097      abstract_ssm              This work describes the various maladies ascribed to masturbation including the supposed occurrence of nuns changing sex.
2257105      abstract_ssm              A work drawing attention to the dire consequences of masturbation form both sexes.
2257106      abstract_ssm              Graham's sexual primer with his treatments for various maladies described.
2618329      abstract_ssm              Report provides general orders and correspondence of public officials and military officers concerning the defense of Philadelphia during the Civil War.
2633096      abstract_ssm              Describes the organization and activities of the militia of New Jersey and includes rosters of officers.
2641807      abstract_ssm              A system of communication based on the Arabic numerals and a few letters made universal by translating the key into any desired language.
```

This one feels like maybe not quite right, but maybe?

**Comment by cdmo** [comment]
Here's a screenshot of a record with a bunch of these new fields, fwiw.

![screenshot](https://user-images.githubusercontent.com/523381/52443680-610adf00-2af4-11e9-9ab5-03bc931fb726.png)

**Comment by banukutlu** [comment]
@ruthtillman can you make sure if the wiki page is up-to-date for note fields? I will review PRs and use it as reference.

**Comment by ruthtillman** [comment]
Yep, I updated earlier and then just ran through it, made a couple quick changes to match what I think we should have... and I think it's good to go!

**Comment by banukutlu** [comment]
@ruthtillman  ```505(???)	Table of Contents``` which subfields? `505agrt`?

**Comment by ruthtillman** [comment]
Updated. The 583 label was getting lost from an unescaped pipe character.

**Comment by mkutch** [comment]
Take a look at `catkey 6054326` as an example with a multiple long 501a fields.

**Comment by ruthtillman** [comment]
I would be happy to look at that one either a) when it's deployed or b) when it's on folks' machines.

**Comment by mkutch** [comment]
@ruthtillman Some more records with multiple long 501/505 fields
`244318,
6054326,
7661249,
21312685,
21341765,
21348156
`

**Comment by banukutlu** [comment]
> @ruthtillman Some more records with multiple long 501/505 fields
> `244318, 6054326, 7661249, 21312685, 21341765, 21348156 `

@mkutch could you add your examples to https://psu.app.box.com/notes/398548730970

**Comment by mkutch** [comment]
@ruthtillman @banukutlu I found a Stanford record with a multiple long 501 fields. 
See Stanford
 https://searchworks.stanford.edu/view/9557727
and the same record in our catalog
 https://blackcat01qa.libraries.psu.edu/catalog/6053392

**Comment by ruthtillman** [comment]
QAd -- things look good. But updated/added 588 to the wiki page. Example record: `25731485`.
