### ISSUE TITLE
Another **Record exceeds maximum export size

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_traject#154]
Did a full extract and now an new record popped up with the error `**Record exceeds maximum export size.   `  I have to dig down and find which record did this. We might want to look into have cataloging sometime look into cleaning up these 8 records if possible as Sirsi suggested.

**Comment by mkutch** [comment]
Found the catkey that caused this error `25380603` .

**Comment by banukutlu** [comment]
Closing this since the record is indexed since

per @mkutch 

> This catkey has been added to the list of special catkeys to be extracted. The record is in production now.
