### ISSUE TITLE
Index fields for Illiad

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#162]
Some of our fields need to be structured differently to be added to Illiad.

We will need to pass the following fields to Illiad (if exist):

- title
- primary author (person/corporation/meeting)
- isbn
- publication date
- OCLC no
- Call number
- where did you find this item cited (we will want to send the new catalog URL)

We will need to add the following indexing:

- publication date (and/or range): `260c:264|*1|c`
- OCLC no: possibly https://github.com/tulibraries/tul_cob/blob/b0e6434ac916775c971bed283dd23b834046ea9f/lib/traject/macros/custom.rb#L528-L542 ? (but only indexing 035, which may repeat, not 979)

(note, we had included publisher/place and edition but per update from Shane these are not openurl compatible w/our system so we can't pass them on)

**Comment by banukutlu** [comment]
@ruthtillman I am assuming we are adding these mappings as new fields and not changing the current logic for the field we use for to populate publication year facet and publication display.

**Comment by ruthtillman** [comment]
@banukutlu correct, these are new fields, not changes.

**Comment by ruthtillman** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/OCLC-Number
