### ISSUE TITLE
Index specialized sublocation for Aeon

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#167]
We will need to index 799a for the sublocation to be passed to Aeon. Sample record: c107

@mkutch needs to first see if this is being extracted or not because it doesn't seem to be in our MARC exports.
 
OR, should we use the staff notes if sending to Aeon? See the staff notes on the response, which would have the right location for each particular item https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCCAT&titleID=107&includeAvailabilityInfo=true&includeItemInfo=true

this seems more accurate

**Comment by ruthtillman** [comment]
Re: the staff note, we'd just need to test a lot to be sure that they're the kind of data we want.

**Comment by mkutch** [comment]
@ruthtillman I've been reading the webservices documentation and there is another webservice variable we can add and turn at end of url .
It is marcEntryFilter and it has values ALL, BRIEF, FULL, NONE, TEMPLATE
This will give us the MARC data! Each value refers to what has been set to display in the policy (we see it when we do a Change Display in the CAT).

https://cat.libraries.psu.edu:9443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&titleID=107&includeAvailabilityInfo=true&includeItemInfo=true&includeBoundTogether=true&marcEntryFilter=ALL

and that's not all. We can even specify a specific field we want.

https://cat.libraries.psu.edu:9443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&titleID=107&includeAvailabilityInfo=true&includeItemInfo=true&includeBoundTogether=true&marcEntryID=799

We can even list the fields we want to return in webservice call so we won't have to index fields if they aren't necessary.

https://cat.libraries.psu.edu:9443/symwsbc/rest/standard/lookupTitleInfo?clientID=BCPAC&titleID=107&includeAvailabilityInfo=true&includeItemInfo=true&includeBoundTogether=true&marcEntryID=245,799,506,264

**Comment by mkutch** [comment]
@ruthtillman It’s best not to use Staff notes field in this case. Staff notes can contain anything (i.e. Hathitrust notes, Digitization notes, etc)

**Comment by ruthtillman** [comment]
@mkutch 👍 this is unfortunate, because it would have allowed us to pair the actual item with the subLocation. Can we ask folks in SCL whether the subLocation field is actually useful when we may be passing the wrong one, since we're only passing one 799 field now? 

- should we pass all 799 fields?
- should we just index the first one since we're only ever passing one?

**Comment by mkutch** [comment]
Last week I cleaned up the marc records which had duplicate 799 fields. Now there should only be one 799 for each bib record.  The 799 field needs to be added to Special Collections Aeon requests because they need it to be on their call slips.
See Jun 26 post above to see how you can get the 799 field via webservice call.

**Comment by ruthtillman** [comment]
Updated the Aeon wiki page.
