### ISSUE TITLE
Records with incompatible encodings error

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#17]
In GitLab by @bzk60 on Aug 21, 2018, 11:41

```
 Exception: Encoding::CompatibilityError: incompatible encodings: UTF-8 and ASCII-8BIT
    org/jruby/RubyString.java:2659:in `<<'
```

* [x]  List of catkeys and subfields with encoding problems - @mxk128 
* [x]  Determine the rules for skipped subfields - @rkt6 
* [x]  Follow up with Jeff Edmunds about a possible clean-up for such records - @rkt6

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 21, 2018, 11:58

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 22, 2018, 09:25

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 22, 2018, 13:45

Setting `Encoding.default_external = "UTF-8"` did not work for us. We will add `provide "marc4j_reader.permissive", true` so that indexing continues instead of throwing an error and failing. With this setting, fields that have corrupt data will be skipped but record will still be indexed.

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Aug 22, 2018, 14:21

mentioned in commit bc6e77399d5bee405fe96096a714935c70b6e247

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 23, 2018, 09:42

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 23, 2018, 09:43

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 23, 2018, 09:44

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 23, 2018, 09:47

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 24, 2018, 11:31

@rkt6 would you mind running traject in your local with this sample doc https://psu.app.box.com/file/312784555565 and upload the resulting log to box here https://psu.app.box.com/folder/52724560586. We would like to see if the subfields with encoding issue will be skipped or not. @mxk128

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Aug 24, 2018, 11:38

Done. demo_output.txt

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 24, 2018, 11:59

@mxk128 check output for 2337355  
```<datafield tag="245" ind1="1" ind2="0"><subfield code="a">Constraints on the structure of the Fila Coste.</subfield><subfield code="ñ">a fold and thrust belt based on low temperature termochronometry Pacific Coast, Costa Rica /</subfield><subfield code="c">by James R. Arthur.</subfield></datafield>```

`Traject::Marc4JReader` is more strict for subfield codes than the default reader?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Aug 30, 2018, 12:48

@rkt6, @mxk128 ran a full index (a month old dump I think Maryam should confirm this) and added two files here https://psu.app.box.com/folder/53004234861 for the list of records with encoding issues. One file only has the catkeys and the other catkeys with skipped subfields. There are some weird catkeys in the list starting with `ocm`. Maryam is checking those right now. I think one she checked has 2 001. We will keep this issue updated about those ones.

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 4, 2018, 17:26

assigning this to @rkt6 since the remaining tasks are for her. fyi @mxk128.

**Comment by banukutlu** [comment]
an updates on cleaning these records up?

**Comment by banukutlu** [comment]
@ruthtillman todo: how to cleanup 245

**Comment by ruthtillman** [comment]
Re: above -- we'll accept errors and non-indexing in fields other than 245/1xx for the time being. In the long-term we need to clean up anything that isn't a 5xx. 5xxs (notes) are our last priority.

**Comment by banukutlu** [comment]
@ruthtillman so we can actually move this to a later MVP then right?

**Comment by banukutlu** [comment]
> Re: above -- we'll accept errors and non-indexing in fields other than 245/1xx for the time being. In the long-term we need to clean up anything that isn't a 5xx. 5xxs (notes) are our last priority.

@ruthtillman moving this out of MVP1, looks more like post initial release?

**Comment by ruthtillman** [comment]
Prepared data cleanup spreadsheet for non-5xx.

**Comment by ruthtillman** [comment]
Checked these should all be done
