### ISSUE TITLE
Make OCLC (035) number and LCCN (010) keyword searchable

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#181]
We need the identifiers solr field to be part of keword search.

## WDDLL

Search for `63164241`  in keyword should pull up the same thing as https://catalog.libraries.psu.edu/catalog?commit=Search&op=AND&all_fields=&title=&author=&subject=&identifiers=63164241+&series=&publisher=&range%5Bpub_date_itsi%5D%5Bbegin%5D=&range%5Bpub_date_itsi%5D%5Bend%5D=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&search_field=advanced

**Comment by ruthtillman** [comment]
Note for when we get to this- we have the first instance of the OCLC # from 035a indexed in keyword but we don't have deprecated ones indexed. We may have 035z fields for former numbers. As part of this, let's add that + 019a (repeatable) which is the other place you can put these.

**Comment by ajkiessl** [comment]
@ruthtillman @banukutlu I think this is done, or at least it was picked up by some other change that may have been done more recently.  I think it's picked up in the `all_text_timv` search: https://github.com/psu-libraries/psulib_blacklight/blob/main/solr/conf/schema.xml#L253 .  I could explicitly add OCLC and LCCN to the keyword search if we think that would be helpful.  The search in the OP works, along with its LCCN search.  I tried a couple other examples and they worked as well.

**Comment by ruthtillman** [comment]
@ajkiessl Just tried a handful--these are now working as expected! Maybe something in our Solr changes/updates.
