### ISSUE TITLE
Address govt publication complication w/university presses

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#186]
When "University" and "Press" aren't together, in the press's name, it still shows up as a government document. "Penn State University Press" would be caught. "University of Michigan Press" would not. Can we change this:

https://github.com/psu-libraries/psulib_traject/blob/80d4014d1f43e39dd1ba0ae917fb8cc790a0ae38/lib/marc_format_processor.rb#L120-L124

to a contains search vs. a phrase search?

Example of what university press names tend to look like: https://catalog.libraries.psu.edu/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&identifiers=&series=&publisher=university+press&f_inclusive%5Bformat%5D%5B%5D=Government+Document&range%5Bpub_date_itsi%5D%5Bbegin%5D=&range%5Bpub_date_itsi%5D%5Bend%5D=&sort=score+desc%2C+pub_date_itsi+desc%2C+title_sort+asc&search_field=advanced&commit=Search

**Comment by banukutlu** [comment]
@ruthtillman is this closed mistakenly, maybe?

**Comment by ruthtillman** [comment]
Yes, I was closing the others and accidentally hit it too. Thanks.

**Comment by ruthtillman** [comment]
Updated the wiki to clarify that the goal of this change is to find every instance of "University" AND "Press" in 264s.

University of Michigan Press and Penn State University Press should both be caught.

**Comment by banukutlu** [comment]
@ruthtillman do we need to consider any non-english representations?

**Comment by ruthtillman** [comment]
Good question -- we do not because we should have English representations of everything, the others will be duplicates.

**Comment by ruthtillman** [comment]
Looks good! Couple edge cases are slipping through but that's a data issue re: catalogers not always including "Press" which isn't a blocker. Huge improvement comparing to current catalog. Thank you!

**Comment by ruthtillman** [comment]
Update -- after more review, I realized we should just limit the test to "University." This will catch some edge cases and while still being sufficient for our needs.

**Comment by ruthtillman** [comment]
this is good!
