### ISSUE TITLE
Index 993 for endowment information

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#189]
First pass at endowment support. See https://github.com/psu-libraries/psulib_blacklight/wiki/Endowments-and-Dedications#keyword-search

Overview:

- 993a & 993n keyword searchable
- some method of directly linking to a search for all 993a - it doesn't have to be in the advanced search dropdown or anything, just a field we can give to Karen S et. al to link to (and also use in the display?)

We would want to check the data first to be sure how that should work.

**Comment by cdmo** [comment]
Related to https://github.com/psu-libraries/psulib_blacklight/issues/432
