### ISSUE TITLE
Mapping materials characteristics (3xx)

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#20]
In GitLab by @rkt6 on Aug 22, 2018, 16:26

To remove (will need to be removed if in Blacklight too)
```
to_field 'material_type_display', extract_marc('300a', :trim_punctuation => true) # from original traject, needs re-evaluation for use. May be replaced by phys_desc_display?

```

Should be replaced by `phys_desc_display` from below.

I've already worked these out previously, but each field below should be reviewed in for whether the punctuation needs to be trimmed or not. If so, add `:trim_punctuation => true`.

```
## work physical characteristics

# 300 / 340 (physical description / physical medium)
to_field "phys_desc_display", extract_marc("300abcefg3:340abcdefhijkmno")

# 380 form of work
to_field "form_work_display", extract_marc("380a")

## work other characteristics

# 310 / 321 (current publication frequency / former publication frequency)
# this version has the dates combined, vs. current and ongoing. However, as former things hould have dates attached and will be secondary, it should work for display.
to_field "frequency_display", extract_marc("310ab:321ab") 

# 385
# review how well these choices work
to_field "audience_display", extract_marc("385ma")

## a/v and print music works

# 306 duration
# this field will be one or more NNNNNN and should be interpreted to HH:MM:SS or even a textual way of reading it
to_field "duration_display", extract_marc("306a")

# 344 sound characteristics
to_field "sound_display", extract_marc("344abcdefgh")

# 383 numeric designation of musical work
to_field "music_numerical_display", extract_marc("383abcde")

# 348 format of notated music
to_field "music_format_display", extract_marc("348a")

# 384  musical key
to_field "music_key_display", extract_marc("384a")

# 382 medium of performance
# this will need to be parsed to be useful, it may need more delicate indexing. It may just require display parsing.
to_field "performance_display", extract_marc("382abdenprst")

# 346 video characteristics
to_field "video_file_display", extract_marc("346ab3")

## digital files

# 347 digital file characteristics
to_field "digital_file_display", extract_marc("347abcdef3")
```

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 4, 2018, 15:51

assigned to @acg44

**Comment by banukutlu** [comment]
In GitLab by @acg44 on Sep 6, 2018, 10:53

Reviewed against sample records and all looks good!

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 6, 2018, 11:19

created branch [`20-index-and-display-materials-characteristics-3xx`](https://git.psu.edu/i-tech/psulib_traject/compare/master...20-index-and-display-materials-characteristics-3xx)

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 6, 2018, 14:02

Fields added:

- phys_desc_display
- form_work_display
- frequency_display
- audience_display
- duration_display
- sound_display
- music_numerical_display
- music_format_display
- music_key_display
- performance_display
- video_file_display
- digital_file_display

Fields removed: 

- material_type_display

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Oct 2, 2018, 10:54

mentioned in merge request !7

**Comment by cdmo** [comment]
@ruthtillman, I'm curious as to what you'd like the display labels to be for these items. I think "description" on [the table here](https://github.com/psu-libraries/psulib_blacklight/wiki/Material-Characteristics-Fields) is mostly what you want but a couple fields look a bit too long. Maybe we should add a column for "Display label" or something? Also, we don't want any of these fields to display in results view, right? Just checking to confirm. I did look around in Box to see if the answer to these questions might be there, but I couldn't find anything.

**Comment by cdmo** [comment]
Also, here are some sample data for the fields you had some followup notes on:

```
90212        frequency_ssm             Semimonthly (except Aug.-Nov.), Dec 1912- | Weekly (except Aug.-Nov.), 1892-July 1912
88680        frequency_ssm             Bimonthly, Mar. 1993- | Quarterly, Feb. 1975-
88700        frequency_ssm             Ten times a year, <2009-> | Nine times a year, Dec. 1997-2008 | Frequency varies, 1967-1994 | Eight times a year, 1995-1996
88915        frequency_ssm             Quarterly.
89342        frequency_ssm             Irregular.
85325        frequency_ssm             3 no. a year.
86013        frequency_ssm             Five no. a year (with separate annual cumulative index). | Bimonthly.
51910        frequency_ssm             Seventeen no. a year, 2003- | Frequency varies, 1972-2002
```

```
75875        performance_ssm           piano
76232        performance_ssm           violin piano
76561        performance_ssm           violin & piano
78218        performance_ssm           piano 1 hand orchestra
78786        performance_ssm           piano 1 violin 1 cello 1 3
90121        performance_ssm           kora
```

All the `306a`s do indeed look like these:
```
2062626      duration_ssm              000315 | 000843 | 000500 | 000422 | 001334 | 000309 | 000430 | 0000407 | 000448 | 001708 | 000618 | 003110 | 000250 | 000143 | 000323 | 000033 | 000211 | 000231 | 000226 | 000512 | 000343 | 000351 | 000356 | 002019 | 001542 | 003253
2062661      duration_ssm              005902 | 012239
2062704      duration_ssm              003400 | 003900
2062706      duration_ssm              000240 | 000230 | 000350 | 000442 | 000153 | 000502 | 000524 | 000710 | 000203 | 000426 | 000200 | 000555
2062734      duration_ssm              011006
```
So we have to choose between displaying these as `HH:MM:SS` or `HH hour(s) MM minute(s) SS second(s)` or something else -- we'd pluralize only when needed of course.

**Comment by ruthtillman** [comment]
@cdmo thanks for the sample data! I just updated the documentation with a label column.

**Comment by cdmo** [comment]
Just a quick sanity check for me: For a record like [2062626](https://blackcat01qa.libraries.psu.edu/catalog/2062626), we can see [in the CAT](https://cat.libraries.psu.edu/uhtbin/cgisirsi/x/0/0/57/5/0?searchdata1=2062626%7BCKEY%7D&searchfield1=GENERAL%5ESUBJECT%5EGENERAL%5E%5E&user_id=WEBSERVER) it used the label "Playing Time" for `306a` (which matches the [MARC definition](https://www.loc.gov/marc/bibliographic/bd306.html) it seems). Is the idea for a record like this one to display all 15 lengths of time as human-readable (i.e., 3 minutes, 15 seconds instead of 000315) for all 15 separated by line breaks? I think this is the case, just want to check. Like, you didn't want all the values summed and then displayed (which for this record is 3 hours, 23 minutes, 50 seconds) instead, right?

A lot of these records seem to have a 306 accompanied by a 500 or a 505 with redundant information about playing time/duration, for what it's worth.

**Comment by cdmo** [comment]
(deleted a question, nevermind!) :)

**Comment by cdmo** [comment]
Ok, cool, thanks, I'll take a whack :)

**Comment by cdmo** [comment]
So here's one pattern:

```
2020723      performance_ssm           violin 2 viola 1 cello 1 4
```

And then there's this kind of stuff:

```
79432        performance_ssm           violin piano
79443        performance_ssm           violin and piano
79454        performance_ssm           violin & piano
```

Sometimes instruments have more then one word:

```
77092        performance_ssm           viola da gamba & harpsichord
1941564      performance_ssm           violins 2 cello double bass
```

Here's another different kind:

```
76406        performance_ssm           Clavichord or lute
```

How about we handle rewriting performance values as a post-release feature? There's just a lot of variation and it would take a bit of rinsing and repeating. [Larger, but not complete, sample](https://psu.app.box.com/notes/380753147211).

**Comment by cdmo** [comment]
And one other thing, @ruthtillman, can you check [the wiki](https://github.com/psu-libraries/psulib_blacklight/wiki/Material-Characteristics-Fields) again and let me know if my assumptions about whether or not these fields are multivalued or not are correct?

**Comment by ruthtillman** [comment]
Having reviewed more data and our current display practice, I'm going to sadly agree that we can improve this as a post-release feature. Perhaps consulting with Bloomington, who worked on this kind of data.

@cdmo your assumption for this field is correct. I'll review the others.

**Comment by ruthtillman** [comment]
@cdmo one trick you can use use is here: https://www.oclc.org/bibformats/en/3xx/382.html the (R) in "382  Medium of Performance (R)" means the field may repeat. (NR) means it may not repeat. Same in LC's MARC documentation, e.g. https://www.loc.gov/marc/bibliographic/bd264.html

Of course if it's (NR) but we're indexing two MARC fields, then it will normally be potentially multi-valued (the only real exception is that 100/110/111 should NEVER have more than one of them occurring .... that said, it sometimes happens 🤷‍♀️ )

**Comment by cdmo** [comment]
Ok, thanks for clearing that up. So shall I add subfield 3 for Musical key?

**Comment by ruthtillman** [comment]
@cdmo updated the wiki page to add a few 3s to different fields. https://github.com/psu-libraries/psulib_blacklight/wiki/Material-Characteristics-Fields/_compare/49f909300c0aefa01db2c9e1fe6e4e45cbfec9a8...cb2b90bb64d9a00d3a7308116a1ee4768ab05a8d will show which

**Comment by cdmo** [comment]
Will do, thanks!

**Comment by banukutlu** [comment]
Two follow up issues from Ruth's QA review will handled by #99 and #208
