### ISSUE TITLE
Set up logging to alert when indexing paused

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#203]
We need improved logging and alerts to notify us when changes, updates, and deletes are not making it from Symphony into Solr. We should update Sematex monitoring so that extracts do not build up.

Triggering use case: If Symphony hourly or daily extracts build up without being indexed, we need to be notified.

Additional cases to consider:

- We need to be notified if Symphony hourly/daily extracts are not being created. Do we have some way for our indexing job to alert us if it's not finding changes in an appropriate amount of time? For example, no changes may occur over a weekend. But other than during the winter break, we should have at least one change within most 3-day spans.

**Comment by cdmo** [comment]
Just wanted to tie this to #180 too because we don't consider our work with the traject pipeline completely finished. Hopefully we can get to this after the MyAccount milestone

**Comment by cdmo** [comment]
we now have an alert setup from Splunk to tell us when a indexing process did not work as it should
