### ISSUE TITLE
Map HathiTrust overlap data

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#204]
Using the overlap file, index data into the Solr collection so faceting is available.

- Volume Identifier - `htid` 
- HathiTrust Record Number - `ht_bib_key`
- Access Code - `access`

## Include Hathi ETAS on/off toggle in `Settings`

When on: access facet is set to online for denies
When off: access facet is not set for denies

https://www.hathitrust.org/how-to-add-etas-records-to-your-catalog#HathiFiles

**Comment by cdmo** [comment]
For what we are trying to do (add records to the access online facet) I don't think we need to add anything to the index, instead we can just do a lookup in the access facet field processing.

**Comment by cdmo** [comment]
@banukutlu and I just chatted for a bit and confirmed we need htid and that will replace the need for the bibapi javascript call we make in blackcat

**Comment by cdmo** [comment]
I'm merging your branch into mine @banukutlu, continue the work

**Comment by cdmo** [comment]
The review of this is covered by #585, so I'm closing this one.
