### ISSUE TITLE
Mapping  genres

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#22]
https://github.com/psu-libraries/psulib_blacklight/wiki/Genre-Fields-Index-and-Display

**Comment by ruthtillman** [comment]
Genre faceting:

Include:
650|*0|v
655|*0|a
655|*7|a IF subfield 2 == lcgft OR fast

Note, we will also need to remove the term Electronic Books

**Comment by banukutlu** [comment]
@ruthtillman do we apply the same conditional `IF subfield 2 == lcgft OR fast` to `655` to genre fields for  keyword search as in faceting and display?
