### ISSUE TITLE
Record is an ETAS record but is not showing the Hathitrust ETAS link

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_traject#224]
Catkey `3689599` doesn't show ETAS link in catalog but does in the CAT. I checked Hathitrust and it has temporary access through ETAS.

**Comment by ruthtillman** [comment]
looks good!

**Comment by cdmo** [comment]
I am closing this one back up because @mkutch created a separate issue for the new ETAS miss she discovered which can be seen at #226
