### ISSUE TITLE
Curbside Pickup change of logic for Hathi Public Domain

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#230]
https://github.com/psu-libraries/psulib_blacklight/wiki/Google-Books-and-HathiTrust-Integration-Links#curbside-pickup-change-of-logic-for-public-domain

eg. catkey: 737403
```
317082719    737403    multi    allow    pd
317082719    737403    multi    deny    ic
317082719    737403    multi    deny    und
```
 should be indexed with deny as ETAS record and I want It would be suppressed during ETAS period.

**Comment by cdmo** [comment]
Just to clarify:

a `multi` with `allow` and `deny` should be indexed with the `ht_bib_key` and be marked as `true` for `etas` and the url to HathiTrust should be appended with the sign in suffix.

The two different parts are the sign in suffix and marking as etas.
