### ISSUE TITLE
Review changing record updates to increase indexing frequency

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#240]
What can we do to increase the frequency of record updates? Things to allow for include possibility of overlaps, etc..

Related ticket:  [Symphony blackcat extracts every 15 min #309](https://github.com/psu-libraries/Symphony/issues/309)

**Comment by cdmo** [comment]
we currently start hourlies at 7am. Do we want to keep it that way or change to 6am?

**Comment by ruthtillman** [comment]
7 is ok now that we have the overnight load
