### ISSUE TITLE
Index 099a so that it's in keyword search

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#241]
Cataloging is making the 099a into a canonical field for mapping special collections accessioning numbers. It does not appear to be indexed in keyword search.

Examples:
* Search for 09715 should get https://catalog.libraries.psu.edu/catalog/16418026
* 09844 should get https://catalog.libraries.psu.edu/catalog/21330529 
* 09981 should get https://catalog.libraries.psu.edu/catalog/26782112

**Comment by ruthtillman** [comment]
If this is something fairly easy to just get into the keyword index (no need to display), then can we add it to current indexing work? If it's more complex, we can wait a little bit on it.

**Comment by cdmo** [comment]
@ruthtillman when I do a search 

* for `09715` https://catalog.libraries.psu.edu/catalog/16418026 shows as the number 2 (out of 2) results.
* for `09844` https://catalog.libraries.psu.edu/catalog/21330529 shows as the number 2 (out of 2) results.
* for `09981` https://catalog.libraries.psu.edu/catalog/26782112 shows as the number 6 (out of 6) results.

So the field is indeed indexed. 

Or is this request for the placement in the search results for these _special collections accessioning numbers_ to be higher? As in the above 3 records should all be _the first_ result in searches for the special collections accessioning number?

**Comment by ruthtillman** [comment]
🤔 weird, I wasn't getting those when I tried it--I was just getting 1 result for those first two, the one with the 856 in it.

It would be helpful if it were weighed higher, yes. Especially since it's a numerical thing so that shouldn't really interfere with other searches.

**Comment by cdmo** [comment]
👍 

Very odd it wasn't there before. I take that these accessioning number identifiers have been around a long time right?

**Comment by ruthtillman** [comment]
totally. I don't know if I searched at a weird time...

**Comment by cdmo** [comment]
🤔 

Side thought: We should make a relevancy testing suite some day just to make sure we're always good with what we expect. 

Anyway, I'm working one raising relevancy for this ID now 👍

**Comment by cdmo** [comment]
@ruthtillman it looks like the `099a` might be used for purposes other than the special collections accessioning number? Like this govdoc: https://catalog.libraries.psu.edu/catalog/55106. This old newspaper (?) has a weird thing going on in the 099a too: https://catalog.libraries.psu.edu/catalog/126675

This is to say maybe we'll be catching other things in the 099a too. I want to confirm that this is okay. To me it seems fine, the end result will be that any value in the `099a` will have a boosted relevancy.

**Comment by ruthtillman** [comment]
Thanks for checking -- yes that should be fine.

**Comment by cdmo** [comment]
this is in QA now... I also wanted to mention that I added this new ID to our advanced search identifiers field, so you can also search for accessioning numbers there and get less noise.

**Comment by ruthtillman** [comment]
Works great! Thank you for the identifiers field add--that's an elegant choice!
