### ISSUE TITLE
Index Open Access to Access

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#245]
Logic: IF 506$2 == star AND 856$7 == 0 THEN add Access == "Open Access"

This will always be at minimum a **second** access status as the material will probably also be Access: "Online." 

linked with https://github.com/psu-libraries/psulib_blacklight/issues/528

**Comment by cdmo** [comment]
this is in QA, but note that the extract is from the 18th, so it's a bit out of date. Figured that was ok for QA purposes.

**Comment by ruthtillman** [comment]
QAd and looks good to me -- asked Jeff E to QA as an expert on the data (and let him know the extract was from 18th) and will see if he notices any issues.

**Comment by ruthtillman** [comment]
Jeff says looks good and he'll keep posting.
