### ISSUE TITLE
Update link indexing to include two blank indicators on 856

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#263]
While not ideal as it provides very little info about the resource linked, the double null indicator for `856|  |` is a valid use case. Because some of the records we're getting from vendors use it, we'll need to add it to our indexing. Treat as a full-text link.

**Comment by banukutlu** [comment]
@ruthtillman do you have an example catkey?

**Comment by ruthtillman** [comment]
Unfortunately, we fixed the catkey where it was reported. @mkutch is this something you could get via a query?

**Comment by mkutch** [comment]
@ruthtillman I'll look... in the meantime approx when was the catkey changed.... I want to see if it still exists in DEV (which hasn't been synched for months) to see what it looks like... So there is no $u subfield?

**Comment by ruthtillman** [comment]
@mkutch catkey is: 6946582 and was only fixed at the end of Oct. Two blank indicators -- there's still a $u.

**Comment by mkutch** [comment]
catkeys
`1174303`
`23786738`
`2206901`
`2187375`

do you need more?

**Comment by banukutlu** [comment]
> catkeys
> `1174303`
> `23786738`
> `2206901`
> `2187375`
> 
> do you need more?

thanks these are good 👍

**Comment by banukutlu** [comment]
@ruthtillman could you please update https://github.com/psu-libraries/psulib_blacklight/wiki/URL-Fields as well?

**Comment by ruthtillman** [comment]
Done!

**Comment by ruthtillman** [comment]
These look great! Good to deploy.
