### ISSUE TITLE
Fix Microform Classification

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#287]
From E.N. email:

```
We started by using the new catalog.  We got 8,661 results for: 
Campus: University Park  
Format: Government Document 
Media Type:  Microfilm/Microfiche 

A search in the legacy CAT brings up 71,340 records for
Material Type: Microfilm/Microfiche
Location: Paterno - 2nd Floor - U.S. Documents
```

(note: the above numbers are for a specific search, we have more total microforms than just 71,340 but after we complete the ticket we should match them in an Advanced search for parameters: `Format: Microfilm/Microfiche` & `Location: Paterno - 2nd Floor - U.S. Docs` - run in CAT as well just to be sure numbers haven't changed in interim.)

Issue identified -- our media format issue relies on MARC fields which are not necessarily present if the Microformat record is a reused print record which has not been properly adapted into a Microformat record. This means that our MARC-based indexing will identify it as a print volume vs. a microformat. This should not affect things related to bound-in. It's actually easy to identify all Microformats using the following criteria:

IF the record includes at least on 949t which has the value MICROFORM, it's of that type.

Because our default use of 949t goes to formats, we can also use this moment to change Microformats from Material Type to Format per request of microformats library (while not strictly ontologically correct, it's something the users who do this search most often have requested and, other than ontological considerations, there's no reason not to).

Steps:

* [x] Ruth update wiki
* [ ] remove MARC-based indexing for Microformats as Material Type
* [ ] add 949t-based indexing for Microformats as Format
* [ ] add format icon for display: https://github.com/psu-libraries/psulib_blacklight/issues/749
* [ ] review spec

sample catkeys: `1477303, 1939940, 1939929`.

Key files:

- MARC based indexing is in: these two lines https://github.com/psu-libraries/psulib_traject/blob/main/lib/marc_media_type_processor.rb#L47-L48 (we need to retain the others in that section) and this line https://github.com/psu-libraries/psulib_traject/blob/main/lib/marc_media_type_processor.rb#L152
  - note: these were supposed to catch properly coded 007 fields and then the 300a was supposed to be a backup for records which didn't have good 007 but at least had been turned into microforms records, which we've learned many have not.
- where we set up the 949t indexing https://github.com/psu-libraries/psulib_traject/blob/main/lib/translation_maps/formats_949t.properties just need to add `MICROFORM = Microfilm/Microfiche`

**Comment by ruthtillman** [comment]
Made updates to wiki so our core documentation is correct.

**Comment by awead** [comment]
@ruthtillman There's also a "Microfile/Microfiche" media type at https://github.com/psu-libraries/psulib_traject/blob/main/lib/marc_media_type_processor.rb#L152. Should that be removed as well?

**Comment by awead** [comment]
@ruthtillman Just for clarification, both L47-L48 _and_ L152 are out?

**Comment by ruthtillman** [comment]
@awead yes, both of them. We're removing it entirely as a "Media Type" and its indexing as such was based on two different kinds of tests.
