### ISSUE TITLE
Update Microfilm indexing to catch other formats

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#303]
Microfilm record indexing currently stops after indexing the one kind of thing but we need to record multiple formats for a record if there's also serials/periodicals on it: https://catalog.libraries.psu.edu/catalog/483004

Essentially wherever it falls in things it should test for microfilms AND test for any other formats which might match.

We're likely to see the following combos: Microfilm/book, Microfilm/serial, Microfilm/archival material.

**Comment by awead** [comment]
It looks like this is having the side effect of adding back in rejected formats from the 6/7 leader, such as "Book" when "Juvenile Book" is already present from the 949t. I'm seeing this with https://catalog.libraries.psu.edu/catalog/4059691 which is one of the test fixtures. Prior to this change, we avoided this problem by simply ignoring the format in the leader if we already had one from the 949t.

If we now have to include that format from the leader, we could selectively reject "Book" for example if "Juvenile Book" is present, and accept all the rest, or alternatively, use other kind of logic to determine which one to let it.

**Comment by ruthtillman** [comment]
Thanks for the analysis, Adam. I've reviewed the formats to see which might get conflated with Book. From what's in formats_949t.properties, it might make more sense to keep ignoring formats 6/7 _unless_ it's Microform vs. the other way around, since one reason we're using it that way is that all of those might contain encoding to test to Book, depending. So maybe an "if not MICROFORM, keep doing what we're doing?"

**Comment by ruthtillman** [comment]
Looks good to me! As mentioned in the meeting, we may find more edge cases, but this is a significant improvement.
