### ISSUE TITLE
mapping publication year facet

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#31]
In GitLab by @rkt6 on Sep 7, 2018, 12:20

Does the marc_publication_date function produce what we actually need for our publication date information? Review what the process does and how well it fits for our use.

Related to #18

**Comment by banukutlu** [comment]
Is this related to #18?

**Comment by banukutlu** [comment]
`marc_publication_date`:

```
# An opinionated algorithm for getting a SINGLE publication date out of marc
    #
    # * Prefers using 008, but will resort to 260c
    # * If 008 represents a date range, will take the midpoint of the range,
    #     only if range is smaller than estimate_tolerance, default 15 years.
    # * Ignores dates below min_year (default 500) or above max_year (this year plus 6 years),
    #     because experience shows too many of these were in error.
```

**Comment by ruthtillman** [comment]
Notes in successive comments. Note 1:

```
 # Okay, nothing from 008, try 260
     if found_date.nil?
       v260c = MarcExtractor.cached("260c", :separator => nil).extract(record).first
       # just try to take the first four digits out of there, we're not going to try
       # anything crazy.
       if m = /(\d{4})/.match(v260c)
         found_date = m[1].to_i
       end
     end
```

We need to also take into account 264|*1|c, because 264 replaces 260, although we still have some old 260s. Only if the second indicator is 1 is it a publication date, though.

**Comment by ruthtillman** [comment]
Reviewed the rest of the logic and I think it will have to do, specifically to power anything date-related in searching/filtering. Otherwise we will simply display what's in the record itself.

**Comment by banukutlu** [comment]
so, publication year facet mapping should check `008`first, if not that, then `264|*1|c`, if not that, then `260c`.
