### ISSUE TITLE
Hourly jobs

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_traject#322]
The hourly jobs need some further refinement.

## TODO

delete hourly files after they've been indexed
automate files into the scratch space in kubernetes
add 100% testing coverage to HourlyIndexer

**Comment by whereismyjetpack** [comment]
As part of #332  we address processing adds, adding tests. As part of another ticket/PR i think we should do 

- [ ] process deletes
- [ ] work with @mkutch to keep kubernetes full_extracts, and hourlies in sync

**Comment by whereismyjetpack** [comment]
As part of #336 we are now processing deletes, we're syncing data from symphony servers.
