### ISSUE TITLE
Add Sidekiq UI for viewing progress

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_traject#323]
Provide a UI for viewing Sidekiq workers.

## What does done look like

- Sidekiq Admin interface at `/sidekiq` from the catalog. This is webauth protected, only ul-dev-team can display it.

**Comment by whereismyjetpack** [comment]
https://github.com/psu-libraries/psulib_traject/pull/325 addresses this, the kubernetes configuration will take the base_url of the deployment, and route `/sidekiq` to the rack configuration in this PR. This code is running in qa `https://catalog.qa.k8s.libraires.psu.edu/sidekiq`
