### ISSUE TITLE
Review from which field to extract the call number from

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#33]
In GitLab by @bzk60 on Sep 10, 2018, 12:06

For `callnum display` should we be extracting `949a` field or `050a`?

Per Maryam
> 050 is lc call number but not every rec has one. If you do a catkey on search 12345 it has no 050 but it has a call number in 949a

Per Ruth
>  We will not use the call numbers in the 949a for faceting. If there is an 050 (library of congress call number), we will index it and use it for sidebar faceting and Browse function. However we will not worry at this point about records which do not have an LC call number. This can be a post-MVP concern. (SUDOCS may be built into traject and Ruth should look into this further.)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 10, 2018, 12:06

assigned to @mxk128

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 10, 2018, 12:08

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 10, 2018, 12:08

changed the description

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 10, 2018, 12:12

My two cents -- it depends on what we're using it for. Preference 050. 949 could be used as backup but it may not have an LC call number. When it comes to actual item display,

However, having an LC call number could be useful for:

- browse
- faceting in the sidebar

Options:

- If no 050, then check 949a.
- See if 949a appropriately matches an LC call number?
- If it does, treat as such.

Issues:

Which 949a should we use? See if any match an LC call number? Use the first which does?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 10, 2018, 12:50

changed title from **Review from which field to extract the call number** to **Review from which field to extract the call number{+ from+}**

**Comment by ruthtillman** [comment]
Evaluating what others do -- it might be useful in the long term to work through more detailed call numbers, but in the short term, let's use something like the following to get the data from the 050a field if it exists:

https://github.com/tulibraries/tul_cob/blob/master/lib/traject/indexer_config.rb#L197-L200

https://github.com/tulibraries/tul_cob/blob/5d4bce2d57b8971d18cb0ae661c251680a453558/lib/traject/macros/custom.rb#L334-L342

**Comment by banukutlu** [comment]
Closing this since we decided to use `050` for call numbers. For more info:  https://github.com/psu-libraries/psulib_blacklight/wiki/Call-Number-Index-and-Display
