### ISSUE TITLE
Generate and index shelf keys for browsing titles 

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#331]
We can use the `title_sort` field for creating a browseable list of titles, but it isn't optimal for display. Instead of trying to have different fields, one for sort, one for display, we can make sorted field that can be "unsorted" later.

## To-Do

Update `title_sort` to retain the trimmed elements, ex: _The Great Gatsby_ becomes _Great Gatsby The_. For the display, the original title is reassembled:

``` ruby
> "Great Gatsby The".split.rotate(-1).join(' ')
=> "The Great Gatsby"
```

**Comment by awead** [comment]
I've updated the description to reflect a new approach. We can update the existing title_sort field so that the original title can be reassembled in the catalog for display.
