### ISSUE TITLE
Add a few fields (still smaller than normal subject) to subject_browse

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#359]
Following up from testing, we should re-add these fields to the subject_browse_facet. These are fairly limited forms (in terms of which letters we're using, this means we can find all books _about_ Karl Marx and his work, for example) and restricted to LC so they should be pretty good for grouping the types of things without leading to too much spread, which we were getting with the original pass.

people:

`600|*0|abcd`
`610|*0|abcd`
`611|*0|abcd`

geography:

`651|*0|agvxyz`

named events and uniform titles:

`630|*0|avxyz`
`647|*0|avxyz`

Or basically just put in:

`600|*0|abcd:610|*0|abcd:611|*0|abcd:651|*0|agvxyz:630|*0|avxyz:647|*0|avxyz`

**Comment by banukutlu** [comment]
@ruthtillman adding the new fields will get us the below, just checking to see if that looks fine to you:

standard_fields:
`600|*0|abcd:610|*0|abcd:611|*0|abcd:630|*0|avxyz:647|*0|avxyz:650|*0|abcdgvxyz:650|*1|abcdgvxyz:650|*3|abcdgvxyz:650|*3|abcdgvxyz:651|*0|agvxyz`

pst_fields: 
`650|*7|abcdgvxyz`

**Comment by ruthtillman** [comment]
Looks about right -- I see we seem to have a duplicate of `650|*3|abcdgvxyz` which was what I put in the original issue. Can we also change that to a `*2` which is what I think I meant? We don't want `\*[4-7]\` but 2 is one our medical folks use...

**Comment by banukutlu** [comment]
@ruthtillman  ok made the change:
`'600|*0|abcd:610|*0|abcd:611|*0|abcd:630|*0|avxyz:647|*0|avxyz:650|*0|abcdgvxyz:650|*1|abcdgvxyz:650|*2|abcdgvxyz:650|*3|abcdgvxyz:651|*0|agvxyz'`

**Comment by ruthtillman** [comment]
Thanks! When it's indexed I'll go look at it.

**Comment by banukutlu** [comment]
@ruthtillman For subject browse, we are taking the max length subjects. I want to clarify that:

If the subject are like below, 

`A-B-C-D`
`A-B-C-D-E`
`E-F`
`1-2-3`
`1-2-3-4-5`

what is our expectation here for the result?

just fyi @awead

**Comment by ruthtillman** [comment]
@banukutlu as long as those subjects are all in subject_facet_browse or whatever we're using for that browse page, that's fine. Because while  encoding Quilts -- Pennsylvania is a different than encoding for Pennsylvania--Centre County, we don't distinguish when doing our subject searching

**Comment by banukutlu** [comment]
> @banukutlu as long as those subjects are all in subject_facet_browse or whatever we're using for that browse page, that's fine. Because while encoding Quilts -- Pennsylvania is a different than encoding for Pennsylvania--Centre County, we don't distinguish when doing our subject searching

With the current logic, those will output  `A-B-C-D-E` and `1-2-3-4-5`, is that what we want 🤔

**Comment by ruthtillman** [comment]
oh yes! Sorry I didn't understand the question, we want A-B-C-D-E and 1-2-3-4-5 or whatever the longest length is

**Comment by ruthtillman** [comment]
(does the above make sense? would it help to show what I expect from a particular catkey?)

**Comment by banukutlu** [comment]
> if 610 is separate then we'd want it to be outputting E-F though

Not sure what you mean by separate 🤔 but I am trying to figure how we should apply the max length rule, like across all subject browse facet fields or each different field like within 650 within 610, etc.

**Comment by ruthtillman** [comment]
separate fields! So yes, it would be applying the same rule across. Here's an example of what I'd expect from https://catalog.libraries.psu.edu/catalog/36139180/marc_view 

```
650 \0 a| Outdoor recreation z| Pennsylvania z| Leonard Harrison State Park v| Maps.
650 \0 a| Outdoor recreation z| Pennsylvania z| Colton Point State Park v| Maps.
651 \0 a| Leonard Harrison State Park (Pa.) v| Maps.
651 \0 a| Colton Point State Park (Pa.) v| Maps.
650 \0 a| Parks z| Pennsylvania v| Maps.

Outdoor recreation -- Pennsylvania -- Colton Point State Park -- Maps
Outdoor recreation -- Pennsylvania -- Leonard Harrison State Park -- Maps
Leonard Harrison State Park (Pa.) -- Maps
Colton Point State Park (Pa.) -- Maps
Parks -- Pennsylvania -- Maps
```
