### ISSUE TITLE
Mapping preceding and succeeding entry fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#37]
[serials wiki page](https://github.com/psu-libraries/psulib_blacklight/wiki/Serials-(Title,-Previous,-and-Successive-Publications))

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Sep 20, 2018, 10:28

created branch [`37-780-785-preceeding-and-succeeding-entry-display-fields`](https://git.psu.edu/i-tech/psulib_traject/compare/master...37-780-785-preceeding-and-succeeding-entry-display-fields)

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Oct 2, 2018, 11:08

mentioned in merge request !9

**Comment by ruthtillman** [comment]
https://github.com/psu-libraries/psulib_blacklight/wiki/Linking-Serials-Fields-(Title,-Previous,-and-Successive-Publications)

**Comment by cdmo** [comment]
@ruthtillman I don't see anywhere how you would like these fields displayed other than to link the text to a search of title. I see 13 proposed fields on this issue, so we'd need them all to have labels. Either that or is the idea that we'd like to combine each set of fields down to one (to make only two multivalued fields)?

**Comment by ruthtillman** [comment]
Updated wiki page with labels. These were already on the single item view fields, so ensured that labels matched fields already listed.

**Comment by banukutlu** [comment]
@ruthtillman could you add more info to search and facet section of the wiki page.  For search, I assume they will be part of keyword search only, nothing else. And probably no facets for these fields but we just need to confirm. thanks!

**Comment by ruthtillman** [comment]
++

**Comment by banukutlu** [comment]
@ruthtillman catkey: 10407665 does it suppose to display a preceding entry? there is no indicator2.

**Comment by ruthtillman** [comment]
@banukutlu I looked up the record in OCLC, it is supposed to have two indicator 0s. I edited the copy in our cat with the correction.
