### ISSUE TITLE
Change 866, 867, 868 subfields to ATOZ (traject method)

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#373]
Testing with Nick uncovered the possibility of other fields being used in the data, particularly `|z`. Since these fields are not thoroughly-documented, it seems like a good use case for the traject method "ATOZ" instead of just listing numbers.

This will index any subfields (that use letters) and, as usual, in the order in which they appear (which is the order the person entering data intended since that's how traditional MARC displays).

Each field should still go to a single string as this is for display only. We may need to test to be sure that spaces between them are appearing correctly.

**Comment by nicktiberi** [comment]
An example record with data in the z subfield is: https://catalog.libraries.psu.edu/catalog/52888/marc_view

The data is shown in the record in the CAT: https://cat.libraries.psu.edu/uhtbin/cgisirsi/?ps=wz4tXmYren/UP-PAT/X/9
