### ISSUE TITLE
MARC field 880 clean-up

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#38]
In GitLab by @mxk128 on Sep 21, 2018, 09:54

An unknown number of erroneous 880 fields exist in The CAT. There will be a need to identify the scope of the errors and investigate strategies for removing the fields in question.

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Sep 21, 2018, 14:00

`selcatalog -60 -30 -oC | perl prtmarc.pl -e880 -oCiteB -t$ > all_880s.txt`

**Comment by banukutlu** [comment]
@ruthtillman any update on this?

**Comment by banukutlu** [comment]
@ruthtillman I am moving this out of MVP1

**Comment by ruthtillman** [comment]
@banukutlu @mkutch when we do the next full extract and traject run, can we get all records with 880 fields generating errors? Just catkeys is enough. I think this would be in the error log. I can then pass it on for review/cleanup

**Comment by banukutlu** [comment]
> @banukutlu @mkutch when we do the next full extract and traject run, can we get all records with 880 fields generating errors? Just catkeys is enough. I think this would be in the error log. I can then pass it on for review/cleanup

sure we can get those catkeys - they will be in our traject logs.  
@cdmo

**Comment by cdmo** [comment]
Here's [a list of catkeys](https://psu.app.box.com/notes/502365106563) from the last index run on prod using the 7/25/19 extract

**Comment by ruthtillman** [comment]
Some are fixed. I sent the rest to Mono team.
