### ISSUE TITLE
Index 653 as Other Subjects 

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#387]
The 653 field is an uncontrolled kind of subject, which means that it functions like a text field vs a hierarchical subject. We will want to index it for display but not apply any special kind of logic.  It only has one subfield, "a" so we're just indexing the `653a`.

We are adding this to the general subject keyword search field `subject_tsim` but not to the hierarchical subjects or subject facet.

| MARC field | expectation |
| --- | --- |
| 653a | free text |

**Comment by banukutlu** [comment]
@ruthtillman Would you be able to give us some example records that have 653a subject?

**Comment by ruthtillman** [comment]
Catkey examples:

- 33188434
- 24149588
- 14742712 (this one has repeating As, which I guess we should be sorting into separate fields?)
- 15969831
- 35155396

**Comment by ruthtillman** [comment]
Looks good!
