### ISSUE TITLE
2168941 mistakenly identified as gov doc?

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#460]
https://catalog.libraries.psu.edu/catalog/2168941 is mistakenly identified as a
government document? 

Reported by [INC2219790](https://pennstate.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=7359e359c3862dd062ca32cf050131ca%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by ruthtillman** [comment]
Scheduled meeting with Elizabeth for Friday. Our primary goal will be to see what we can do with the record to stop it from appearing here, but if there's nothing within the rules then we may have to revisit the indexing. Hoping it can be solved without any dev work.

**Comment by ruthtillman** [comment]
Reviewed with Elizabeth, something we could fix in the record! Will email Nathan Monday when the actual index has updated
