### ISSUE TITLE
Course Reserves extract

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#48]
per Ruth: 

From our 10/30 meeting. Breaking out structure, problem, and questions in course reserves.

We have two kinds of _thing_ which go on course reserve. The first is existing records, when we already have something, with a full bib record (or purchase the item but get the full bib record), and then put one or more copies on reserve. The second are brief title records, which include title/author/maybe some notes. These are created for items which are specifically added to the catalog to be put on course reserve. They generally are shadowed.

Note, 592s for course reserves/bookplates

# Structure

- we have separate records for course reserves, which have course ID, course description, and course instructor.
- items are linked to these courses in a different module, there's nothing in the 949, other than that the location would be reserve.
- the item ID appears to be the best field for cross-reference.

# Problems

- when we extract a regular bib, we need to indicate if it's on course reserve and link it up with the right course
- we need to extract and index the shadowed brief title records for things like instructor copies
- we will probably need to run a second indexing pass for just course reserve information.

# Questions/Things to Explore

Once we answer these, can people add answers in the comments and check off the item?

1.  @mkutch  and Chris: is there a way you can use the Sirsi report selection criteria to figure out how we can extract the brief title records?
1.  @mkutch  and Chris: walk through how people make items unavailable/take them off reserve and what this looks like in our data.
1.  How do we extract and create records _only_ for current courses and remove them when they're done? How do other Sirsi-using institutions, like Stanford (whose course records seem similar to ours) extract and create these records?
1. What data fields (location, item ID, etc.?) would we need to extract and how would we index them in order to run a second indexing update process to create/manage course reserves?

Correspondence with Stanford: https://psu.app.box.com/notes/341399689070 & their repo https://github.com/sul-dlss/course_reserves

**Comment by mkutch** [comment]
1. 1. We're leaning towards seltools instead of a Symphony report and run this as a cron job to run every X mins.
2. Course reserves are identified by the Reserve Control's Status (i.e. CURRENT) and Reserve's Stage (i.e. ACTIVE) . The Stage determines whether it appears in the catalog under a courser reserve search.  The Status (ie. ON-RESERVE) determines if the circulation rule kicks in.
3. After the initial extract of current ones we are planning to compare incrementals and decide.

**Comment by banukutlu** [comment]
Since we are planning to have a seperate extract for course reserves and seems that we will not need to change/edit the main extract for course reserves so I am moving this to MVP3.
