### ISSUE TITLE
Setup testing suite

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#60]

**Comment by cdmo** [comment]
@banukutlu I tested your feature branch for this locally and it worked with the fixture.mrc data. @mkutch is removing 13 or so records that cannot be made public and adding a change to the 590 and shifting holding information from 949 to 999 all at once to kill a few birds. Once that's in place, I'll add to my `ci` branch and see what Travis says.

**Comment by cdmo** [comment]
@banukutlu the other thing that I've been thinking about in regards to testing is fixtures vs. stubbing with Traject. SUL seems to do both:

[Fixture-based](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/spec/lib/traject/config/author_spec.rb)

[Stubbing/mocking](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/spec/lib/traject/config/format_main_spec.rb)

Stubbing/mocking would be nice in that we can just assemble the needed subfields ourselves, without having to worry about correct fixture data that is free to use in the public.

**Comment by banukutlu** [comment]
@cdmo yup we can def. do it!

**Comment by banukutlu** [comment]
Connected to #42

**Comment by cdmo** [comment]
We should probably setup CI too for Traject, eh?

**Comment by banukutlu** [comment]
> We should probably setup CI too for Traject, eh?

yeas, will add an issue for it.
