### ISSUE TITLE
Incrementals cron

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#63]
check this: https://github.com/traject/traject/blob/master/doc/batch_execution.md

- ~Update add/update and delete~ Manage crons
- ~Change path in scripts to run from traject/scripts~
- Update documentation https://github.com/psu-libraries/psulib_traject/wiki/Add,-Update-and-Delete-Records 

Requires #71

**Comment by cdmo** [comment]
Some data will be exported to blackcat01qa, once that's there we'll process it with Traject

**Comment by cdmo** [comment]
see https://github.com/psu-stewardship/psulib_blacklight_deploy/issues/29

**Comment by cdmo** [comment]
Closing this since the PR was reviewed for Traject. https://github.com/psu-libraries/psulib_traject/pull/135 should have closed it.
