### ISSUE TITLE
Update URLs notfulltext regex

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#8]
* [x] **Maryam**: export all 856s with both indicators and subfields. If possible, export all 856s which do NOT have second indicator of 0 or 2. (Otherwise we can sort on second indicator and select only some).
* [x] **Ruth**:  Improve regular expressions matching for table of contents, etc., in URLs notfulltext by reviewing our records. Take contents of subfield z and subfield 3 where second indicator is NOT 0 or 2. Add as a project in OpenRefine. Use OpenRefine's grouping to evaluate possible fields to add to notfulltext.
* [x]  Change URLs notfulltext regex as `addendum|appendices|appendix|appendixes|cover|excerpt|executive summary|index` . https://github.com/psu-libraries/psulib_traject/blob/f8b6c7aededb444966aa17ff8ba79d9da333b3a2/lib/traject/psulib_config.rb#L323

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 19, 2018, 09:50

changed the description

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 10:45

marked the task ****Maryam**: export all 856s with both indicators and subfields. If possible, export all 856s which do NOT have second indicator of 0 or 2. (Otherwise we can sort on second indicator and select only some).** as completed

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 11:27

marked the task ****Maryam**: export all 856s with both indicators and subfields. If possible, export all 856s which do NOT have second indicator of 0 or 2. (Otherwise we can sort on second indicator and select only some).** as incomplete

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 11:46

marked the task ****Maryam**: export all 856s with both indicators and subfields. If possible, export all 856s which do NOT have second indicator of 0 or 2. (Otherwise we can sort on second indicator and select only some).** as completed

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 11:46

@rkt6 I exported all the 856s in a pipe delimited file (3650972 lines) on box https://psu.box.com/s/na1dsbwce8e87ldwp8nyeeqf3rtf447b.
 Name of the file is  all_856s_issue8.txt

catkey|indicators|856 subfield

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 11:47

assigned to @rkt6 and unassigned @mxk128

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Jun 20, 2018, 11:48

I have the full list of 856s. Let me know if you want me to upload it to box also.

**Comment by banukutlu** [comment]
In GitLab by @rkt6 on Jun 20, 2018, 12:02

@mxk128 yes, thank you please put it in Box!

**Comment by ruthtillman** [comment]
Hi all,

sorry for the delay on this. Can we add:

addendum|appendices|appendix|appendixes|cover|excerpt|executive summary|index

to the "notfulltext"? https://github.com/psu-libraries/psulib_traject/blob/f8b6c7aededb444966aa17ff8ba79d9da333b3a2/lib/traject/psulib_config.rb#L323
