### ISSUE TITLE
Bound withs - Add parent info to generated 591 to display

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#83]
The display of the "Bound in" tag at the title level is misleading without item info.
eg. catkey [485144](https://blackcat01qa.libraries.psu.edu/catalog/485144). This title has 289 items under it but only one item is bound with another title(catkey [11749683](https://blackcat01qa.libraries.psu.edu/catalog/11749683)).

Add `949a`, `949c`, `949t` to generated 591s:

`591 a|Parent title c| Parent catkey t| Parent format n| Parent call number  c. copy number` 

so to display as below:

949a 949c (949t) bound in [title], e.g.

`AY67.N5W7 1922-24 c. 1 (MICROFORM) bound in The World almanac and encyclopedia`

or

`Microfilm D285 reel.478 no.3575 c.1 (MICROFORM) bound in The high-caste Hindu woman / With introduction by Rachel L. Bodley`

Also use translation map for `591t` format.

_Originally posted by @banukutlu in https://github.com/psu-libraries/psulib_traject/issues/42#issuecomment-456944505_

**Comment by mkutch** [comment]
I noticed another issue. See https://blackcat01qa.libraries.psu.edu/catalog/988373. This has a bound with item but isn't showing up. I noticed the librarian view doesn't list all the 949s nor the 591. I went back to the extract and saw this record was broken down into 8 marc records (by catalogdump). Since the 591 build happens after the catalogdump it is on the 8th marc record. Checked with the extract and it looks like the librarian view is showing only the 7th marc record.
I can show you what I mean if this sounds confusing.

**Comment by ruthtillman** [comment]
To-dos from 1/29 meeting:

@banukutlu - run script to combine with the mhlds and see how these a) index, b) combine in the record (put resulting combined MARC record and index debug result in Box?)

@mkutch see how/whether Stanford handles it when there's a number of libraries. Are they grouped by library in display? We may need to look at searchworks code / ask Shelley or a front-end dev how they're managed.

me - review MARC fields 853, 863, 867, 868, check in with John Hamilton. Check IU display. View web services result for these records.

**Comment by ruthtillman** [comment]
Update: re 853, 863, 867, 868 -- they are not registered as catalog tags (whereas 852 https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?852,1 and 866 are https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?866,1 ). So I didn't need to check with John. Also looking at extracts we only seem to have to worry about 852/866.

**Comment by ruthtillman** [comment]
Update: IU displays a list of summary holdings by library: https://iucat.iu.edu/catalog/4159565 and then the actual holdings/availability below. Given our number of locations, this seems unlikely to work for us.

And web services doesn't include any location summaries _in the default response I was getting_.

**Comment by mkutch** [comment]
I emailed Shelley and she replied back with

> A great example is https://searchworks.stanford.edu/view/3195844. Yes, we group them by library.

**Comment by ruthtillman** [comment]
Fantastic, then @banukutlu @cdmo you can follow up with the logic + any questions for the devs? We'll want to look at our own data first, but I think that this is a better way of presenting it than the "list alllll the summaries" and then "list allll the holdings separately" for our use case.

**Comment by mkutch** [comment]
@banukutlu I added the parent info to the extract and created sample records out on box. I didn't add the copy. I noticed the copies seemed to be 1. We can look more into it and what it means.

**Comment by cdmo** [comment]
@mkutch which one is it? I see files here: https://psu.app.box.com/folder/53004724072 and https://psu.app.box.com/folder/64944165646

**Comment by cdmo** [comment]
It looks like it's supposed to be this one: [blackcat_boundwith_20190129_sample.mrc](https://psu.box.com/s/7e1trgr609h0oyhvt7dk9h9tbzg0eimy)

**Comment by ruthtillman** [comment]
Ruth, add translation map.

**Comment by ruthtillman** [comment]
I created a translation map and added it. It should be noted that this map is _only_ for bound-in, as I didn't include item types which couldn't have a bound-in (e.g. equipment). I also shortened some of the property names in order to improve display for this use purpose.

**Comment by cdmo** [comment]
I've updated [the Bound-with wiki page](https://github.com/psu-libraries/psulib_blacklight/wiki/Bound-With-in-Linked-Notes) to reflect this issue, fyi.

Some nuances in the change, so let me know if I'm off.

**Comment by cdmo** [comment]
So let's say we have the following:

![screenshot 2019-02-05 16 28 33](https://user-images.githubusercontent.com/523381/52305494-3ccbc880-2963-11e9-92e8-e8811576453f.png)

How should this look in Blacklight?

Bound in: QE75.C5 no.256-269 (Book) bound in [Sedimentation in small reservoirs on the San Rafael Swell, Utah /](link-to-the-parent item)
Binding notes: Bound with: Sedimentation in small reservoirs on the San Rafael Swell, Utah / N.J. King and M.M. Mace.


Binding notes: QE75.C5 no.256-269 (Book) bound in [Sedimentation in small reservoirs on the San Rafael Swell, Utah /](link-to-the-parent item)
Bound with: Sedimentation in small reservoirs on the San Rafael Swell, Utah / N.J. King and M.M. Mace.

Something else?
