### ISSUE TITLE
Add a combining reader for split records

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#86]
Per Maryam
> I noticed another issue. See https://blackcat01qa.libraries.psu.edu/catalog/988373. This has a bound with item but isn't showing up. I noticed the librarian view doesn't list all the 949s nor the 591. I went back to the extract and saw this record was broken down into 8 marc records (by catalogdump). Since the 591 build happens after the catalogdump it is on the 8th marc record. Checked with the extract and it looks like the librarian view is showing only the 7th marc record.
I can show you what I mean if this sounds confusing.

_Originally posted by @mkutch in https://github.com/psu-libraries/psulib_traject/issues/83#issuecomment-456969097_

Requires #88

**Comment by banukutlu** [comment]
@mkutch can you upload an example extract for a such record on box?

**Comment by banukutlu** [comment]
Per Ruth 
> Talked with Kutchemeshgi, Maryam this morning about the issue of split records in extracts with a lot of holdings and contacted Stanford to see who there works on theirs. Dawn at NCSU hasn't tackled it yet. Also, Maryam in a follow-up to our conversation--actual holdings would be displayed from WebServices, so it's more an issue for the bound-withs and anything else which uses the 949s for indexing...which still makes it a big issue, but when looking at others' catalogs they'd still display all the appropriate holdings... it just wouldn't be in librarianview/in their indexing that relies on holdings

**Comment by ruthtillman** [comment]
Emailed person at Stanford responsible for their Sirsi exports. Copied Maryam and Banu.

**Comment by banukutlu** [comment]
Stanford's solution: They added a class that combines the records (https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/readers/marc_combining_reader.rb). 

traject config: 
https://github.com/sul-dlss/searchworks_traject_indexer/blob/eab76f7c71bf1650189bf9bbeee580e4b19f5c40/lib/traject/config/sirsi_config.rb#L254-L267

**Comment by mkutch** [comment]
@banukutlu @cdmo  I found this which looks like their code in solr marc before the moved/converted their code to traject? Their algorithm is documented too. 

https://github.com/solrmarc/stanford-solr-marc/blob/master/core/src/org/solrmarc/marc/CombineMultBibsMhldsReader.java

**Comment by mkutch** [comment]
@banukutlu @cdmo  I found this which looks like their code in solr marc before they moved/converted their code to traject? Their algorithm is documented too and can be helpful. 

https://github.com/solrmarc/stanford-solr-marc/blob/master/core/src/org/solrmarc/marc/CombineMultBibsMhldsReader.java

**Comment by banukutlu** [comment]
@ruthtillman @cdmo @mkutch 
I tried Stanford's class on my local by changing `999` to `949` and it seems to be working. We need to try with different extracts as well. But I want to confirm the MHLD fields that we need to merge in. These are the fields Stanford uses `852 853 863 866 867 868 949`.

**Comment by ruthtillman** [comment]
Update: IU displays a list of summary holdings by library: https://iucat.iu.edu/catalog/4159565 and then the actual holdings/availability below. Given our number of locations, this seems unlikely to work for us.

And web services doesn't include any location summaries _in the default response I was getting_.

**Comment by banukutlu** [comment]
per Ruth

> Update: re 853, 863, 867, 868 -- they are not registered as catalog tags (whereas 852 https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?852,1 and 866 are https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?866,1 ). So I didn't need to check with John. Also looking at extracts we only seem to have to worry about 852/866.

**Comment by mkutch** [comment]
I emailed Shelley from Stanford and she replied back

>    A great example is https://searchworks.stanford.edu/view/3195844. Yes, we group them by library.

**Comment by banukutlu** [comment]
per Ruth

> Fantastic, then @banukutlu @cdmo you can follow up with the logic + any questions for the devs? We'll want to look at our own data first, but I think that this is a better way of presenting it than the "list alllll the summaries" and then "list allll the holdings separately" for our use case.

**Comment by mkutch** [comment]
@ruth I am seeing the 852/866 field in Marc holdings which are also being displayed in the CAT. See below, one the marc holdings field of `catkey 88730` . Christopher Walker could tell us more how/why they use them.

![image](https://user-images.githubusercontent.com/43478453/51938703-c0257100-23db-11e9-9962-681b71b59212.png)

**Comment by ruthtillman** [comment]
Per Christopher, 867 are Supplemental Materials and 868 indexes.

**Comment by banukutlu** [comment]
> Per Christopher, 867 are Supplemental Materials and 868 indexes.

@ruthtillman so, are we gonna merge these fields? if so they will be in librarian view.

**Comment by ruthtillman** [comment]
@banukutlu yes -- can we talk/look at a sample of how they'd look when merging, though? I'm trying to figure out how we might distinguish these.

**Comment by ruthtillman** [comment]
Ok -- let's export/combine the following fields:

- 852
- 866
- 867
- 868

... and let's see what they look like and how linking of fields can be done. Linking is generally done with subfield 8s. We will want to see if we can group them. We can then use the library code in the 852 to pair with the library codes from the web services availability report.
