### ISSUE TITLE
Add Marc Holdings to the Bib extract

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_traject#88]
this is to add the summary holdings (mhld fields) to the extract.

**Comment by ruthtillman** [comment]
Update: re 853, 863, 867, 868 -- they are not registered as catalog tags (whereas 852 https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?852,1 and 866 are https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?866,1 ). So I didn't need to check with John. Also looking at extracts we only seem to have to worry about 852/866.

**Comment by mkutch** [comment]
I emailed Shelley from Stanford and she replied back

> A great example is https://searchworks.stanford.edu/view/3195844. Yes, we group them by library.

**Comment by banukutlu** [comment]
per Ruth

> Update: re 853, 863, 867, 868 -- they are not registered as catalog tags (whereas 852 https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?852,1 and 866 are https://cat.libraries.psu.edu/uhtbin/Lists/this_tags_info?866,1 ). So I didn't need to check with John. Also looking at extracts we only seem to have to worry about 852/866.

**Comment by banukutlu** [comment]
@maryam could you update our sample records file as well so that we have some sample summary holdings?

**Comment by banukutlu** [comment]
@mkutch could you also update the wiki doc pls? https://github.com/psu-libraries/psulib_traject/wiki/Full-and-Incremental-Extracts-from-Symphony

**Comment by mkutch** [comment]
@banukutlu I put 2 new sample files on box.
