### ISSUE TITLE
Media types mapping

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#97]
https://github.com/psu-libraries/psulib_blacklight/wiki/Media-Types

**Comment by banukutlu** [comment]
@ruthtillman are we gonna have a default value for the ones that are not caught by our rules

**Comment by ruthtillman** [comment]
No, I think in cases where format and media type match -- e.g. a book that's a physical book ... we'll not add on. But if the book is a microfilm, etc. For some it'll always have a media type, like Video.

**Comment by banukutlu** [comment]
@mkutch could you pls extract 21588551 for me?
