### ISSUE TITLE
Add 362a mapping as part of materials characteristics

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#99]
Related to #20

e.g. 2250556

**Comment by cdmo** [comment]
@ruthtillman "Dates of Publication and/or Sequential Designation" appears to be a new field. Just wanted to confirm it's not a change to an existing or a replacement. Also, where should it show up in [the ordered list of fields](https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields)?

**Comment by ruthtillman** [comment]
@cdmo added it to just after the join/split section for records since it's related.

**Comment by ruthtillman** [comment]
looks good.
